@host = localhost
@port = 8000
@url = /v1/groceries
### Create
POST http://{{host}}:{{port}}{{url}}
content-type: application/json

{
    "name": "apple",
    "quantity": 3
}

### Create
PUT http://{{host}}:{{port}}{{url}}
Content-Type: application/json

{
    "name": "apple",
    "quantity": 5
}

### Get list
GET http://{{host}}:{{port}}{{url}}
Content-Type: application/json

### Delete
DELETE http://{{host}}:{{port}}{{url}}
content-type: application/json

{
    "name": "apple"
}

### Healthcheck
GET http://{{host}}:{{port}}/health